### ISSUE TITLE
Problem with CmCaReT

### ISSUE THREAD

**Issue by Daijobou** [christiaan/tinymce-codemirror#26]
I can't explain the reason, but I have two chrome with same version number, but one of it show me in source code this html code:

`<span class="CmCaReT" style="display: none;">�</span>`

and after close, I have a invisible span in my text and open source code again, I have two of this lines. Both browser tested on the identical tinymce and same page. After many STRG+F5 its disappear. Any clue for a reason?

**Comment by thomich** [comment]
Hey @Daijobou 

Thanks for reporting.
I hope you use latest code.. and do you also cleared browser Cache?

What about doing same in other browser? Fiefox, Vivaldi?
What OS you use for this Chrome versions?
> Same OS for both or different OS's

thanks for reply

Regards
thomi

**Comment by dupont-kedama** [comment]
I have same trouble and `saveCursorPosition:true` dose not work.
It has occurred always on my PC.
In Windows7 + Chrome57 / IE11 / Firefox52 . (Cleared browser cache)
With TinyMCE 4.5.6 + CodeMirror for TinyMCE4 Version 1.5.1 + codemirror-5.25.0.

Can I do something else?

**Comment by dariusj18** [comment]
Same here

Windows 10 + Chrome 59
TinyMCE 4.6.4, CodeMirror 4.8 (from repo)

**Comment by RickJelier** [comment]
I ran into this problem as well, I decided to find out what was happening.
The problem doesn't occur when you use
`var html = editor.getContent({format: 'raw'});`

However the problem does occur when using the default `source_view: true`

This is because the source viewer changes the order of the attributes of the element, therefore the regex is not working that is used to replace the span. (see image)

![regex will never work](https://user-images.githubusercontent.com/8720127/34198717-a75ed7ce-e56b-11e7-9d3b-05cd2c14250b.png)

**Comment by dupont-kedama** [comment]
Thank you RickJelier.

I can't understand how to use `var html = editor.getContent({format: 'raw'});`.
My code is 
```
var options = {
  selector: "#myid",
  language: "ja",
  plugins: [.... codemirror....],
  codemirror: {
    indentOnInit: true,
    path: 'codemirror-5.25.0',
    saveCursorPosition: true
  },
  ....
};
tinymce.init(options);
```
Can I use that?

**Comment by thomich** [comment]
Please check: https://github.com/christiaan/tinymce-codemirror/issues/46
